/**
 * Builds src/map/geo.json: SVG path data for the "Where we build" map (MapJourney.jsx).
 * Source: Natural Earth via the world-atlas package (public domain).
 *
 *   npm run build:map
 *
 * Everything shares one Web-Mercator plane, 1000 units wide (360°), cropped to 80°N – 56°S,
 * so the world view, the magnifier and the close-up zoom are all just different viewBoxes.
 *   world   110m land + borders for the whole map (hidden inside the region box)
 *   region  10m land, borders and Egypt for 23°E–38°E, 21°N–33°N (the part you zoom into)
 *
 * It also writes src/map/governorates.json: Egypt's 27 governorates from Natural Earth's 10m
 * admin-1 layer (public domain), used to frame a project's location map on its governorate.
 * The source file (~40 MB) is downloaded once into scripts/.cache/.
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature, merge, mesh } from 'topojson-client';
import { geoArea, geoGraticule, geoMercator, geoPath } from 'd3-geo';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const atlas = (name) => JSON.parse(readFileSync(resolve(root, 'node_modules/world-atlas', name), 'utf8'));

const WIDTH = 1000;
const SCALE = WIDTH / (2 * Math.PI);
const TOP_LAT = 80;
const BOTTOM_LAT = -56;
const mercY = (lat) => SCALE * Math.log(Math.tan(Math.PI / 4 + (lat * Math.PI) / 360));
const Y0 = mercY(TOP_LAT);
const HEIGHT = +(Y0 - mercY(BOTTOM_LAT)).toFixed(2);
const project = ([lon, lat]) => [WIDTH / 2 + (SCALE * lon * Math.PI) / 180, Y0 - mercY(lat)];

const REGION = { west: 23, east: 38, south: 21, north: 33 };
const [rx0, ry0] = project([REGION.west, REGION.north]);
const [rx1, ry1] = project([REGION.east, REGION.south]);

/** Path serializer that rounds and drops points closer than `eps` to the previous one. */
function serializer(digits, eps) {
  let out = '';
  let px = 0;
  let py = 0;
  let pending = null;
  const f = (n) => +n.toFixed(digits);
  return {
    moveTo(x, y) { out += `M${f(x)} ${f(y)}`; px = x; py = y; pending = null; },
    lineTo(x, y) {
      if (Math.hypot(x - px, y - py) < eps) { pending = [x, y]; return; }
      out += `L${f(x)} ${f(y)}`; px = x; py = y; pending = null;
    },
    closePath() { if (pending) out += `L${f(pending[0])} ${f(pending[1])}`; out += 'Z'; pending = null; },
    arc() {},
    result() { const r = out; out = ''; return r; },
  };
}

/**
 * d3 treats a ring's winding as meaning: some Natural Earth polygons come wound the other way,
 * which d3 reads as "the whole globe except this island" and clips into a filled box.
 * Flip any polygon larger than a hemisphere.
 */
function rewind(geo) {
  const fix = (coords) => (geoArea({ type: 'Polygon', coordinates: coords }) > 2 * Math.PI ? coords.map((r) => [...r].reverse()) : coords);
  const g = geo.type === 'FeatureCollection' ? geo.features[0].geometry : geo.type === 'Feature' ? geo.geometry : geo;
  if (g.type === 'Polygon') return { type: 'Polygon', coordinates: fix(g.coordinates) };
  if (g.type === 'MultiPolygon') return { type: 'MultiPolygon', coordinates: g.coordinates.map(fix) };
  return g;
}

function pathFor({ clip, digits, eps }) {
  const projection = geoMercator().scale(SCALE).translate([WIDTH / 2, Y0]).precision(0.05);
  projection.clipExtent(clip);
  const ctx = serializer(digits, eps);
  const path = geoPath(projection, ctx);
  return (geo) => { path(geo); return ctx.result(); };
}

// World (110m)
const c110 = atlas('countries-110m.json');
const worldPath = pathFor({ clip: [[0, 0], [WIDTH, HEIGHT]], digits: 1, eps: 0.25 });
const world = {
  land: worldPath(rewind(merge(c110, c110.objects.countries.geometries))),
  borders: worldPath(mesh(c110, c110.objects.countries, (a, b) => a !== b)),
  graticule: worldPath(geoGraticule().step([15, 15]).extent([[-180, BOTTOM_LAT], [180, TOP_LAT + 0.01]])()),
};

// Region (10m)
const c10 = atlas('countries-10m.json');
const l10 = atlas('land-10m.json');
const regionPath = pathFor({ clip: [[rx0, ry0], [rx1, ry1]], digits: 3, eps: 0.006 });
const egypt10 = c10.objects.countries.geometries.find((g) => g.properties?.name === 'Egypt');
const region = {
  box: [rx0, ry0, rx1 - rx0, ry1 - ry0].map((n) => +n.toFixed(3)),
  land: regionPath(rewind(feature(l10, l10.objects.land))),
  borders: regionPath(mesh(c10, c10.objects.countries, (a, b) => a !== b)),
  egypt: regionPath(rewind(feature(c10, egypt10))),
};

const out = {
  source: 'Natural Earth via world-atlas (public domain). Generated by scripts/build-map.mjs.',
  width: WIDTH, height: HEIGHT, scale: +SCALE.toFixed(6), y0: +Y0.toFixed(6), world, region,
};
const file = resolve(root, 'src/map/geo.json');
mkdirSync(dirname(file), { recursive: true });
writeFileSync(file, JSON.stringify(out));
const kb = (s) => `${(s.length / 1024).toFixed(1)} KB`;
console.log(`geo.json ${kb(JSON.stringify(out))} · world land ${kb(world.land)} · region land ${kb(region.land)} · egypt ${kb(region.egypt)}`);

// Governorates (Natural Earth 10m admin-1, Egypt only)
const ADMIN1_URL = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_1_states_provinces.geojson';
const admin1File = resolve(root, 'scripts/.cache/ne_admin1.geojson');
if (!existsSync(admin1File)) {
  console.log('downloading Natural Earth admin-1 (~40 MB)…');
  mkdirSync(dirname(admin1File), { recursive: true });
  const res = await fetch(ADMIN1_URL);
  if (!res.ok) throw new Error(`admin-1 download failed: ${res.status}`);
  writeFileSync(admin1File, Buffer.from(await res.arrayBuffer()));
}
const admin1 = JSON.parse(readFileSync(admin1File, 'utf8'));
const govPath = pathFor({ clip: [[rx0, ry0], [rx1, ry1]], digits: 2, eps: 0.02 });
const govBounds = geoPath(geoMercator().scale(SCALE).translate([WIDTH / 2, Y0]));
const governorates = admin1.features
  .filter((f) => f.properties.adm0_a3 === 'EGY')
  .map((f) => {
    const shape = rewind(f);
    const [[x0, y0], [x1, y1]] = govBounds.bounds(shape);
    return {
      id: f.properties.iso_3166_2,
      name: { en: `${f.properties.name_en} Governorate`, ar: f.properties.name_ar },
      box: [x0, y0, x1, y1].map((n) => +n.toFixed(3)),
      d: govPath(shape),
    };
  })
  .sort((a, b) => a.id.localeCompare(b.id));
const govFile = resolve(root, 'src/map/governorates.json');
writeFileSync(govFile, JSON.stringify({
  source: 'Natural Earth 10m admin-1 states and provinces (public domain). Generated by scripts/build-map.mjs.',
  governorates,
}));
console.log(`governorates.json ${kb(readFileSync(govFile, 'utf8'))} · ${governorates.length} governorates`);
